package com.tca;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

import com.tca.entities.Student;

public class App 
{
    public static void main(String[] args) 
    {
        Configuration configuration = null;
        SessionFactory sessionFactory = null;
        Session session = null;
        Transaction transaction = null;
        
        try
        {
        	configuration = new Configuration().configure();
        	sessionFactory = configuration.buildSessionFactory();
        	session = sessionFactory.openSession();
        	transaction = session.beginTransaction();
        	
        	Student student = (Student)session.load(Student.class, 202);
        	
        	
        	/*
        	  load(): Is lazy. It does not hit the database immediately. Instead, it returns a "Proxy" object (a placeholder). The actual SQL query is fired only when you try to access a property of that object (like student.getName()) other than the ID.
        	  load(): Throws an ObjectNotFoundException if the data is missing when you try to access it. It assumes the data must exist.
        	  load() returns a Proxy object. A proxy is a dynamic subclass generated by Hibernate at runtime. It looks like your object and has the ID set, but all other fields are empty.

Why? It saves a database trip. If you only need the object reference (for example, to set a foreign key on another object), the proxy is sufficient, and no DB query is needed.

        	 */
        	session.delete(student);
        	transaction.commit();
        }
        catch(Exception e)
        {
        	transaction.rollback();
        	e.printStackTrace();
        }
        finally
        {
        	session.close();
        	sessionFactory.close();
        }
    }
}
